### ISSUE TITLE
Not obeying .swiftlint.yml configuration

### ISSUE THREAD

**Issue by oddysee** [mailiam/SublimeLinter-contrib-swiftlint#1]
My .swiftlint.yml file has this configuration -

<img width="177" alt="screen shot 2016-05-31 at 9 15 14 am" src="https://cloud.githubusercontent.com/assets/899902/15659598/63f55032-2710-11e6-817e-26cc30e8af12.png">

Using other editors with Swiftlint enabled has them doing the right thing, ignoring these rules.

However, this plugin ignores it completely.

<img width="634" alt="screen shot 2016-05-31 at 9 19 06 am" src="https://cloud.githubusercontent.com/assets/899902/15659623/db45ff10-2710-11e6-9c8d-2383cb40c64f.png">

**Comment by mailiam** [comment]
Thanks @oddysee,
I will have a look in to it.

**Comment by mailiam** [comment]
@oddysee ~~I couldn't reproduce your problem.
Could you `swiftlint version` in Terminal for me?
My installed version is 0.10.0.~~

Oh never mind the fix is on the way.
