### ISSUE TITLE
swiftlint autocorrect

### ISSUE THREAD

**Issue by franciscolourenco** [mailiam/SublimeLinter-contrib-swiftlint#2]
Is there an option or command to execute swiftlint's autocorrect feature?

```
autocorrect   Automatically correct warnings and errors
```

**Comment by mailiam** [comment]
sorry for such late reply 😅 

I don't think SublimeLinter supports autocorrection feature (https://github.com/SublimeLinter/SublimeLinter/issues/80) please let me know if otherwise.
